#!/usr/bin/env python3
from __future__ import annotations

import csv
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent
CSV_PATH = BASE_DIR / "premier_league_players_2026.csv"


NAME_MAP = {
    ("伯恩茅斯", "Adams, Tyler Shaan"): "泰勒·亚当斯",
    ("伯恩茅斯", "Adli, Amine"): "阿德利",
    ("伯恩茅斯", "Bevan, Owen Lucas"): "欧文·贝文",
    ("伯恩茅斯", "Brooks, David Robert"): "戴维·布鲁克斯",
    ("伯恩茅斯", "Christie, Ryan"): "瑞安·克里斯蒂",
    ("伯恩茅斯", "Cook, Lewis John"): "刘易斯·库克",
    ("伯恩茅斯", "De Lima Barbosa, Francisco Evanilson"): "埃瓦尼尔松",
    ("伯恩茅斯", "Dennis, William Jonathon"): "威廉·丹尼斯",
    ("伯恩茅斯", "Diakite, Bafode"): "迪亚基特",
    ("伯恩茅斯", "Forster, Fraser Gerard"): "弗雷泽·福斯特",
    ("伯恩茅斯", "Hill, James"): "詹姆斯·希尔",
    ("伯恩茅斯", "Kluivert, Justin Dean"): "贾斯廷·克鲁伊维特",
    ("伯恩茅斯", "Mandas, Christos"): "曼达斯",
    ("伯恩茅斯", "Petrovic, Djorde"): "彼得罗维奇",
    ("伯恩茅斯", "Scott, Alex Jay"): "亚历克斯·斯科特",
    ("伯恩茅斯", "Senesi Baron, Marcos Nicolas"): "塞内西",
    ("伯恩茅斯", "Smith, Adam James"): "亚当·史密斯",
    ("伯恩茅斯", "Tavernier, Marcus Joseph"): "马库斯·塔弗尼耶",
    ("伯恩茅斯", "Truffert, Adrien Lillan Gaetan"): "特吕费尔",
    ("伯恩茅斯", "Unal, Enes"): "于纳尔",

    ("阿斯顿维拉", "Bailey, Leon Patrick"): "莱昂·贝利",
    ("阿斯顿维拉", "Barkley, Ross"): "巴克利",
    ("阿斯顿维拉", "Bizot, Marco"): "比佐特",
    ("阿斯顿维拉", "Buendia Stati, Emiliano"): "布恩迪亚",
    ("阿斯顿维拉", "Cash, Matthew Stuart"): "马蒂·卡什",
    ("阿斯顿维拉", "Digne, Lucas"): "迪涅",
    ("阿斯顿维拉", "Elliott, Harvey Daniel James"): "埃利奥特",
    ("阿斯顿维拉", "Francisco Torres, Pau"): "保·托雷斯",
    ("阿斯顿维拉", "Garcia Robledo, Andres"): "安德烈斯·加西亚",
    ("阿斯顿维拉", "Kamara, Boubacar Bernard"): "卡马拉",
    ("阿斯顿维拉", "Konsa, Ezri Ngoyo"): "孔萨",
    ("阿斯顿维拉", "Maatsen, Ian Ethan"): "马特森",
    ("阿斯顿维拉", "Martinez Romero, Damian Emiliano"): "达米安·马丁内斯",
    ("阿斯顿维拉", "McGinn, John"): "麦金",
    ("阿斯顿维拉", "Mings, Tyrone Deon"): "明斯",
    ("阿斯顿维拉", "Mvom Onana, Amadou Ba Z"): "奥纳纳",
    ("阿斯顿维拉", "Nilsson Lindelof, Victor Jorgen"): "林德洛夫",
    ("阿斯顿维拉", "Rogers, Morgan Elliot"): "罗杰斯",
    ("阿斯顿维拉", "Sancho, Jadon Malik"): "桑乔",
    ("阿斯顿维拉", "Soares De Paulo, Douglas Luiz"): "道格拉斯·路易斯",
    ("阿斯顿维拉", "Tielemans, Youri Marion"): "蒂勒曼斯",
    ("阿斯顿维拉", "Watkins, Oliver George Arthur"): "沃特金斯",

    ("布伦特福德", "Ajer, Kristoffer Vassbakk"): "阿耶尔",
    ("布伦特福德", "Balcombe, Ellery Ronald"): "巴尔科姆",
    ("布伦特福德", "Collins, Nathan"): "柯林斯",
    ("布伦特福德", "Cox, Matthew Aidan"): "马修·考克斯",
    ("布伦特福德", "Damsgaard, Mikkel Krogh"): "达姆斯高",
    ("布伦特福德", "Dasilva, Pelenda Joshua Tunga"): "达席尔瓦",
    ("布伦特福德", "Freitas Gouveia De Carvalho, Fabio Leandro"): "卡瓦略",
    ("布伦特福德", "Henderson, Jordan Brian"): "亨德森",
    ("布伦特福德", "Henry, Rico"): "里科·亨利",
    ("布伦特福德", "Hickey, Aaron Buchanan"): "希基",
    ("布伦特福德", "Janelt, Vitaly"): "亚内尔特",
    ("布伦特福德", "Jensen, Mathias"): "延森",
    ("布伦特福德", "Kelleher, Caoimhin Odhran"): "凯莱赫",
    ("布伦特福德", "Lewis-Potter, Keane William"): "刘易斯-波特",
    ("布伦特福德", "Nascimento Rodrigues, Igor Thiago"): "伊戈尔·蒂亚戈",
    ("布伦特福德", "Nelson, Reiss"): "纳尔逊",
    ("布伦特福德", "Ouattara, Dango Aboubacar Faissal"): "瓦塔拉",
    ("布伦特福德", "Pinnock, Ethan Rupert"): "皮诺克",
    ("布伦特福德", "Schade, Kevin"): "沙德",
    ("布伦特福德", "Valdimarsson, Hakon Rafn"): "瓦尔迪马尔松",
    ("布伦特福德", "Van Den Berg, Sepp"): "范登贝尔赫",

    ("布莱顿", "Ayari, Yasin"): "阿亚里",
    ("布莱顿", "Boscagli, Olivier"): "博斯卡利",
    ("布莱顿", "De Cuyper, Maxim Peter"): "德库珀",
    ("布莱顿", "Dos Santos De Paulo, Igor Julio"): "伊戈尔",
    ("布莱顿", "Dunk, Lewis Carl"): "邓克",
    ("布莱顿", "Gomez Amarilla, Diego Alexander"): "迭戈·戈麦斯",
    ("布莱顿", "Gross, Pascal Alexander"): "格罗斯",
    ("布莱顿", "Kadioglu, Ferdi Erenay"): "卡迪奥卢",
    ("布莱顿", "March, Soloman Benjamin"): "马奇",
    ("布莱顿", "Milner, James Phillips"): "米尔纳",
    ("布莱顿", "Mitoma, Kaoru"): "三笘薰",
    ("布莱顿", "O'Riley, Matthew Sean"): "奥赖利",
    ("布莱顿", "Rushworth, Carl Andrew"): "拉什沃思",
    ("布莱顿", "Rutter, Georginio"): "吕特尔",
    ("布莱顿", "Steele, Jason Sean"): "斯蒂尔",
    ("布莱顿", "Van Hecke, Jan Paul"): "范黑克",
    ("布莱顿", "Veltman, Joel Ivo"): "费尔特曼",
    ("布莱顿", "Verbruggen, Bart"): "费布鲁亨",
    ("布莱顿", "Webster, Adam Harry"): "韦伯斯特",
    ("布莱顿", "Welbeck, Daniel"): "维尔贝克",
    ("布莱顿", "Wieffer, Mats Henrik Berne"): "维弗尔",

    ("伯恩利", "Amdouni, Mohamed Zeki"): "阿姆杜尼",
    ("伯恩利", "Anthony, Jaidon"): "安东尼",
    ("伯恩利", "Barnes, Ashley"): "巴恩斯",
    ("伯恩利", "Broja, Armando"): "布罗亚",
    ("伯恩利", "Dubravka, Martin"): "杜布拉夫卡",
    ("伯恩利", "Edwards, Marcus"): "马库斯·爱德华兹",
    ("伯恩利", "Ekdal, Hjalmar"): "埃克达尔",
    ("伯恩利", "Estève, Maxime"): "埃斯特夫",
    ("伯恩利", "Flemming, Zian"): "弗莱明",
    ("伯恩利", "Foster, Lyle Brent"): "福斯特",
    ("伯恩利", "Hartman, Quilindschy"): "哈特曼",
    ("伯恩利", "Humphreys, Bashir"): "汉弗莱斯",
    ("伯恩利", "Larsen, Jacob Bruun"): "布鲁恩·拉森",
    ("伯恩利", "Laurent, Joshua Ishaele Jacob-Heron"): "洛朗",
    ("伯恩利", "Mejbri, Hannibal"): "汉尼拔",
    ("伯恩利", "Pires Silva, Lucas"): "卢卡斯·皮雷斯",
    ("伯恩利", "Roberts, Connor"): "康纳·罗伯茨",
    ("伯恩利", "Tchaouna, Loum"): "查乌纳",
    ("伯恩利", "Tresor Ndayishimiye, Mike"): "特雷索尔",
    ("伯恩利", "Tuanzebe, Axel"): "图安泽贝",
    ("伯恩利", "Walker, Kyle Andrew"): "凯尔·沃克",
    ("伯恩利", "Ward-Prowse, James Michael Edward"): "沃德-普劳斯",
    ("伯恩利", "Worrall, Joseph Adrian"): "沃勒尔",

    ("切尔西", "Adarabioyo, abdul-Nasir Oluwatosin"): "阿达拉比奥尤",
    ("切尔西", "Badiashile Mukinayi, Benoit Ntambue"): "巴迪亚西勒",
    ("切尔西", "Caicedo Corozo, Moises Isaac"): "凯塞多",
    ("切尔西", "Chalobah, Trevoh Tom"): "查洛巴",
    ("切尔西", "Cucurella Saseta, Marc"): "库库雷利亚",
    ("切尔西", "Delap, Liam Rory"): "德拉普",
    ("切尔西", "Fernandez, Enzo Jeremias"): "恩佐·费尔南德斯",
    ("切尔西", "Fofana, Wesley Tidjan"): "福法纳",
    ("切尔西", "Gusto, Malo Arthur"): "古斯托",
    ("切尔西", "James, Reece"): "里斯·詹姆斯",
    ("切尔西", "Jorgensen, Filip"): "约根森",
    ("切尔西", "Junqueira De Jesus, Joao Pedro"): "若昂·佩德罗",
    ("切尔西", "Lomba Neto, Pedro"): "佩德罗·内托",
    ("切尔西", "Lynch Sanchez, Robert"): "罗伯特·桑切斯",
    ("切尔西", "Palmer, Cole"): "帕尔默",
    ("切尔西", "Samuels Colwill, Levi Lamar"): "科尔威尔",

    ("水晶宫", "Benitez, Walter Daniel"): "贝尼特斯",
    ("水晶宫", "Clyne, Nathaniel Edward"): "克莱因",
    ("水晶宫", "Devenny, Justin"): "德文尼",
    ("水晶宫", "Doucoure, Cheick Oumar"): "杜库雷",
    ("水晶宫", "Guessand, Evann Ludovic Vidjannagni"): "盖桑",
    ("水晶宫", "Henderson, Dean Bradley"): "迪恩·亨德森",
    ("水晶宫", "Hughes, William James"): "威尔·休斯",
    ("水晶宫", "Johnson, Brennan Price"): "布伦南·约翰逊",
    ("水晶宫", "Kamada, Daichi"): "镰田大地",
    ("水晶宫", "Lacroix, Maxence Guy"): "拉克鲁瓦",
    ("水晶宫", "Larsen, Jørgen Strand"): "拉森",
    ("水晶宫", "Lerma, Jefferson"): "莱尔马",
    ("水晶宫", "Mateta, Jean-Philippe"): "马特塔",
    ("水晶宫", "Matthews, Remi Luke"): "雷米·马修斯",
    ("水晶宫", "Mitchell, Tyrick"): "米切尔",
    ("水晶宫", "Munoz Mejia, Daniel"): "穆尼奥斯",
    ("水晶宫", "Nketiah, Edward Keddar"): "恩凯蒂亚",
    ("水晶宫", "Pino Santos, Yeremy Jesus"): "皮诺",
    ("水晶宫", "Riad Dnanou, Chadi"): "里亚德",
    ("水晶宫", "Richards, Christopher Jeffrey"): "克里斯·理查兹",
    ("水晶宫", "Sarr, Ismaila"): "萨尔",
    ("水晶宫", "Sosa, Borna"): "索萨",
    ("水晶宫", "Uche, Christantus Ugonna"): "乌切",

    ("埃弗顿", "Alcaraz Durán, Carlos Jonas"): "阿尔卡拉斯",
    ("埃弗顿", "Barry, Thierno Mamadou"): "巴里",
    ("埃弗顿", "Branthwaite, Jarrad Paul"): "布兰斯韦特",
    ("埃弗顿", "Coleman, Seamus"): "科尔曼",
    ("埃弗顿", "Dewsbury-Hall, Kiernan Frank"): "杜斯伯里-霍尔",
    ("埃弗顿", "Garner, James David"): "加纳",
    ("埃弗顿", "Gomes Betuncal, Norberto Bercique"): "安德烈·戈麦斯",
    ("埃弗顿", "Grealish, Jack Peter"): "格拉利什",
    ("埃弗顿", "Gueye, Idrissa Gana"): "盖耶",
    ("埃弗顿", "Iroegbunam, Timothy Emeka"): "伊罗格布纳姆",
    ("埃弗顿", "Keane, Michael Vincent"): "迈克尔·基恩",
    ("埃弗顿", "King, Thomas Lloyd"): "汤姆·金",
    ("埃弗顿", "McNeil, Dwight James Matthew"): "麦克尼尔",
    ("埃弗顿", "Mykolenko, Vitalii"): "米科连科",
    ("埃弗顿", "Ndiaye, Iliman-Cheikh Baroy"): "恩迪亚耶",
    ("埃弗顿", "O'Brien, Jake Patrick"): "奥布莱恩",
    ("埃弗顿", "Patterson, Nathan Kenneth"): "帕特森",
    ("埃弗顿", "Pickford, Jordan Lee"): "皮克福德",
    ("埃弗顿", "Röhl, Merlin"): "勒尔",
    ("埃弗顿", "Tarkowski, James Alan"): "塔尔科夫斯基",
    ("埃弗顿", "Travers, Mark John"): "特拉弗斯",
    ("埃弗顿", "Welch, Reece Belfield"): "韦尔奇",

    ("富勒姆", "Andersen, Joachim Christian"): "安德森",
    ("富勒姆", "Bassey, Calvin"): "巴锡",
    ("富勒姆", "Berge, Sander Gard Bolin"): "贝格",
    ("富勒姆", "Bobb, Oscar"): "奥斯卡·鲍勃",
    ("富勒姆", "Cairney, Thomas"): "凯尔尼",
    ("富勒姆", "Castagne, Timothy"): "卡斯塔涅",
    ("富勒姆", "Chukwueze, Samuel Chimerenka"): "丘库埃泽",
    ("富勒姆", "Cuenca Barreno, Jorge"): "昆卡",
    ("富勒姆", "Diop, Issa Laye Lucas Jean"): "迪奥普",
    ("富勒姆", "Iwobi, Alexander Chuka"): "伊沃比",
    ("富勒姆", "Jiménez Rodríguez, Raúl Alonso"): "希门尼斯",
    ("富勒姆", "Lecomte, Benjamin Pascal"): "勒孔特",
    ("富勒姆", "Leno, Bernd"): "莱诺",
    ("富勒姆", "Lukic, Sasa"): "卢基奇",
    ("富勒姆", "Muniz Carvalho, Rodrigo"): "穆尼斯",
    ("富勒姆", "Reed, Harrison James"): "里德",
    ("富勒姆", "Robinson, Antonee"): "罗宾逊",
    ("富勒姆", "Sessegnon, Kouassi Ryan"): "塞塞尼翁",
    ("富勒姆", "Smith Rowe, Emile"): "史密斯·罗",
    ("富勒姆", "Tete, Kenny Joelle"): "泰特",
    ("富勒姆", "Wilson, Harry"): "哈里·威尔逊",

    ("利兹联", "Aaronson, Brenden Russell"): "阿伦森",
    ("利兹联", "Ampadu, Ethan Kwame Colm Raymond"): "安帕杜",
    ("利兹联", "Bijol, Jaka"): "比约尔",
    ("利兹联", "Bogle, Jayden Ian"): "博格尔",
    ("利兹联", "Bornauw, Sebastiaan"): "博尔瑙",
    ("利兹联", "Byram, Samuel Mark"): "拜拉姆",
    ("利兹联", "Cairns, Alex Thomas"): "凯恩斯",
    ("利兹联", "Calvert-Lewin, Dominic"): "勒温",
    ("利兹联", "Darlow, Karl"): "达洛",
    ("利兹联", "Gnonto, Degnand Wilfried"): "尼奥托",
    ("利兹联", "Gruev, Ilia"): "格鲁耶夫",
    ("利兹联", "Gudmundsson, Gabriel Johan"): "古德蒙松",
    ("利兹联", "James, Daniel Owen"): "丹尼尔·詹姆斯",
    ("利兹联", "Justin, James MIchael"): "贾斯廷",
    ("利兹联", "Longstaff, Sean David"): "肖恩·朗斯塔夫",
    ("利兹联", "Meslier, Illan Stephane"): "梅斯利耶",
    ("利兹联", "Nmecha, Lukas Okechukwu"): "恩梅查",
    ("利兹联", "Okafor, Noah Arinzechukwu"): "奥卡福",
    ("利兹联", "Perri, Lucas Estella"): "佩里",
    ("利兹联", "Piroe, Joel Mohammed Ramzan"): "皮罗",
    ("利兹联", "Rodon, Joseph Peter"): "罗东",
    ("利兹联", "Stach, Anton Levi"): "施塔赫",
    ("利兹联", "Struijk, Pascal Augustus"): "斯特鲁伊克",
    ("利兹联", "Tanaka, Ao"): "田中碧",

    ("利物浦", "Beck, Owen Michael"): "欧文·贝克",
    ("利物浦", "Becker, Alisson Ramses"): "阿利松",
    ("利物浦", "Bradley, Conor"): "布拉德利",
    ("利物浦", "Chiesa, Federico"): "基耶萨",
    ("利物浦", "Davies, Harvey"): "哈维·戴维斯",
    ("利物浦", "Ekitiké, Hugo Timothée"): "埃基蒂克",
    ("利物浦", "Endo, Wataru"): "远藤航",
    ("利物浦", "Frimpong, Jeremie"): "弗林蓬",
    ("利物浦", "Gakpo, Cody"): "加克波",
    ("利物浦", "Gomez, Joseph David"): "戈麦斯",
    ("利物浦", "Gravenberch, Ryan Jiro"): "赫拉芬贝赫",
    ("利物浦", "Isak, Alexander"): "伊萨克",
    ("利物浦", "Jones, Curtis"): "柯蒂斯·琼斯",
    ("利物浦", "Kerkez, Milos"): "凯尔凯兹",
    ("利物浦", "Konate, Ibrahima"): "科纳特",
    ("利物浦", "Mac Allister, Alexis"): "麦卡利斯特",
    ("利物浦", "Mamardashvili, Giorgi"): "马马尔达什维利",
    ("利物浦", "Ramsay, Calvin"): "拉姆齐",
    ("利物浦", "Robertson, Andrew"): "罗伯逊",
    ("利物浦", "Salah, Mohamed"): "萨拉赫",
    ("利物浦", "Szoboszlai, Dominik"): "索博斯洛伊",
    ("利物浦", "Van Dijk, Virgil"): "范戴克",
    ("利物浦", "Williams, Rhys"): "里斯·威廉姆斯",
    ("利物浦", "Woodman, Frederick John"): "伍德曼",

    ("曼联", "Bayindir, Altay"): "巴因德尔",
    ("曼联", "Borges Fernandes, Bruno Miguel"): "布鲁诺·费尔南德斯",
    ("曼联", "Casimiro, Carlos Henrique"): "卡塞米罗",
    ("曼联", "Dalot Teixeira, Jose Diogo"): "达洛特",
    ("曼联", "De Ligt, Matthijs"): "德利赫特",
    ("曼联", "Diallo, Amad"): "阿马德",
    ("曼联", "Heaton, Thomas David"): "希顿",
    ("曼联", "Maguire, Harry Jacob"): "马奎尔",
    ("曼联", "Malacia, Tyrell Johannes Chicco"): "马拉西亚",
    ("曼联", "Martinez, Lisandro"): "利桑德罗·马丁内斯",
    ("曼联", "Mazraoui, Noussair"): "马兹拉维",
    ("曼联", "Mbeumo, Bryan Tetsadong Marceau"): "姆贝乌莫",
    ("曼联", "Mount, Mason Tony"): "芒特",
    ("曼联", "Santos Carneiro da Cunha, Matheus"): "库尼亚",
    ("曼联", "Sesko, Benjamin"): "塞斯科",
    ("曼联", "Shaw, Luke Paul Hoare"): "卢克·肖",
    ("曼联", "Ugarte Ribeiro, Manuel"): "乌加特",
    ("曼联", "Zirkzee, Joshua Orobosa"): "齐尔克泽",

    ("纽卡斯尔联", "Apolinario De Lira, Joelinton Cassio"): "乔林顿",
    ("纽卡斯尔联", "Barnes, Harvey Lewis"): "巴恩斯",
    ("纽卡斯尔联", "Botman, Sven Adriaan"): "博特曼",
    ("纽卡斯尔联", "Burn, Daniel Johnson"): "丹·伯恩",
    ("纽卡斯尔联", "Elanga, Anthony David Junior"): "伊兰加",
    ("纽卡斯尔联", "Gillespie, Mark Joseph"): "吉莱斯皮",
    ("纽卡斯尔联", "Gordon, Anthony Michael"): "戈登",
    ("纽卡斯尔联", "Guimaraes Rodriguez Moura, Bruno"): "吉马良斯",
    ("纽卡斯尔联", "Kraft, Emil Henry Kristoffer"): "克拉夫特",
    ("纽卡斯尔联", "Livramento, Valentino"): "利夫拉门托",
    ("纽卡斯尔联", "Murphy, Jacob Kai"): "墨菲",
    ("纽卡斯尔联", "Osula, William Idamudia Daugaard"): "奥苏拉",
    ("纽卡斯尔联", "Pope, Nicholas David"): "波普",
    ("纽卡斯尔联", "Ramsdale, Aaron"): "拉姆斯代尔",
    ("纽卡斯尔联", "Ramsey, Jacob Matthew Decourcey"): "拉姆齐",
    ("纽卡斯尔联", "Ruddy, John Thomas Gordon"): "鲁迪",
    ("纽卡斯尔联", "Schar, Fabian Lukas"): "舍尔",
    ("纽卡斯尔联", "Thiaw, Malick"): "蒂奥",
    ("纽卡斯尔联", "Tonali, Sandro"): "托纳利",
    ("纽卡斯尔联", "Trippier, Kieran John"): "特里皮尔",
    ("纽卡斯尔联", "Willock, Joseph George"): "威洛克",
    ("纽卡斯尔联", "Wissa, Yoane"): "维萨",
    ("纽卡斯尔联", "Woltemade, Nick"): "沃尔特马德",

    ("诺丁汉森林", "Aina, Temitayo Olufisayo Olaoluwa"): "艾纳",
    ("诺丁汉森林", "Anderson, Elliot Junior"): "埃利奥特·安德森",
    ("诺丁汉森林", "Awoniyi, Taiwo Micheal"): "阿沃尼伊",
    ("诺丁汉森林", "Bakwa, Dilane Ros-Anderson"): "巴夸",
    ("诺丁汉森林", "Costa Dos Santos, Murillo Santiago"): "穆里略",
    ("诺丁汉森林", "Dominguez, Nicolas Martin"): "多明格斯",
    ("诺丁汉森林", "Gibbs-White, Morgan Anthony"): "吉布斯-怀特",
    ("诺丁汉森林", "Giraud-Hutchinson, Omari Elijah"): "哈钦森",
    ("诺丁汉森林", "Gunn, Angus Fraser James"): "冈恩",
    ("诺丁汉森林", "Hudson-Odoi, Callum James"): "哈德森-奥多伊",
    ("诺丁汉森林", "Lucca, Lorenzo"): "卢卡",
    ("诺丁汉森林", "Maciel Da Cruz, Igor Jesus"): "伊戈尔·热苏斯",
    ("诺丁汉森林", "McAtee, James John"): "麦卡蒂",
    ("诺丁汉森林", "Milenkovic, Nikola"): "米伦科维奇",
    ("诺丁汉森林", "Ndoye, Dan"): "恩多耶",
    ("诺丁汉森林", "Netz, Luca"): "内茨",
    ("诺丁汉森林", "Ortega Moreno, Stefan"): "奥尔特加",
    ("诺丁汉森林", "Sangare, Ibrahim"): "桑加雷",
    ("诺丁汉森林", "Savona, Nicolo"): "萨沃纳",
    ("诺丁汉森林", "Sels, Matz Willy Els"): "泽尔斯",
    ("诺丁汉森林", "Williams, Neco Shay"): "内科·威廉姆斯",
    ("诺丁汉森林", "Wood, Christopher Grant"): "伍德",
    ("诺丁汉森林", "Yates, Ryan James"): "耶茨",

    ("桑德兰", "Alderete Fernandez, Omar Federico"): "阿尔德雷特",
    ("桑德兰", "Ba, Abdoullah Mustapha"): "巴",
    ("桑德兰", "Ballard, Daniel George"): "巴拉德",
    ("桑德兰", "Brobbey, Brian Ebenezer Adjai"): "布罗贝伊",
    ("桑德兰", "Cirkin, Dennis"): "瑟金",
    ("桑德兰", "Geertruida, Lutsharel Emiliano"): "海特勒伊达",
    ("桑德兰", "Hume, Trai"): "休姆",
    ("桑德兰", "Isidor, Wilson"): "伊西多尔",
    ("桑德兰", "Le Fée, Enzo Jérémy"): "勒费",
    ("桑德兰", "Mandava, Reinildo Isnard"): "雷尼尔多",
    ("桑德兰", "Moore, Simon William"): "西蒙·摩尔",
    ("桑德兰", "Mukiele Mulere, Nordi"): "穆基勒",
    ("桑德兰", "Mundle, Romaine Lee"): "蒙德尔",
    ("桑德兰", "O'Nien, Luke Terry"): "奥尼恩",
    ("桑德兰", "Poveda-Ocampo, Ian Carlo"): "波韦达",
    ("桑德兰", "Ramirez, Nilson David Angulo"): "安古洛",
    ("桑德兰", "Traore, Bertrand Isidore"): "贝特朗·特劳雷",
    ("桑德兰", "Xhaka, Granit"): "扎卡",

    ("热刺", "Austin, Brandon Anthony"): "奥斯汀",
    ("热刺", "Bentancur, Rodrigo"): "本坦库尔",
    ("热刺", "Bissouma, Yves"): "比苏马",
    ("热刺", "Danso, Kevin"): "丹索",
    ("热刺", "Davies, Benjamin Thomas"): "本·戴维斯",
    ("热刺", "De Andrade, Richarlison"): "理查利森",
    ("热刺", "Dragusin, Radu-Matei"): "德拉古辛",
    ("热刺", "Gallagher, Conor"): "加拉格尔",
    ("热刺", "Kinsky, Antonin"): "金斯基",
    ("热刺", "Kolo Muani, Randal"): "科洛·穆阿尼",
    ("热刺", "Kudus, Mohammed"): "库杜斯",
    ("热刺", "Kulusevski, Dejan"): "库卢塞夫斯基",
    ("热刺", "Lobo Alves P. Costa Palhinha Goncalves, Joao Maria"): "帕利尼亚",
    ("热刺", "Maddison, James"): "麦迪逊",
    ("热刺", "Porro Sauceda, Pedro Antonio"): "波罗",
    ("热刺", "Romero, Cristian Gabriel"): "罗梅罗",
    ("热刺", "Sarr, Pape Matar"): "萨尔",
    ("热刺", "Simons, Xavi Quentin Shay"): "哈维·西蒙斯",
    ("热刺", "Solanke-Mitchell, Dominic Ayodele"): "索兰克",
    ("热刺", "Spence, Diop Djed"): "斯彭斯",
    ("热刺", "Udogie, Iyenoma Destiny"): "乌多吉",
    ("热刺", "Van De Ven, Micky"): "范德芬",
    ("热刺", "Vicario, Guglielmo"): "维卡里奥",

    ("西汉姆联", "Areola, Alphonse Francis"): "阿雷奥拉",
    ("西汉姆联", "Bowen, Jarrod"): "鲍文",
    ("西汉姆联", "Castellanos Gimenez, Valentin Mariano Jose"): "卡斯特利亚诺斯",
    ("西汉姆联", "Disasi Mhakinis Belho, Axel"): "迪萨西",
    ("西汉姆联", "Fabianski, Lukasz Marek"): "法比安斯基",
    ("西汉姆联", "Hermansen, Mads"): "赫尔曼森",
    ("西汉姆联", "Kilman, Maximilian"): "基尔曼",
    ("西汉姆联", "Magassa, Soungoutou"): "马加萨",
    ("西汉姆联", "Mavropanos, Konstantinos"): "马夫罗帕诺斯",
    ("西汉姆联", "Potts, Freddie"): "波茨",
    ("西汉姆联", "Soucek, Tomas"): "绍切克",
    ("西汉姆联", "Summerville, Crysencio Jilbert Sylverio Cirro"): "萨默维尔",
    ("西汉姆联", "Todibo, Jean-Clair Dimitri Roger"): "托迪博",
    ("西汉姆联", "Traore Diarra, Adama"): "特劳雷",
    ("西汉姆联", "Walker-Peters, Kyle Leonardus"): "沃克-彼得斯",
    ("西汉姆联", "Wan-Bissaka, Aaron"): "万-比萨卡",
    ("西汉姆联", "Wilson, Callum Eddie Graham"): "卡勒姆·威尔逊",

    ("狼队", "Agbadou, Badobre Emmanuel Elysee Djedje"): "阿格巴杜",
    ("狼队", "Arias Andrade, Jhon Adolfo"): "阿里亚斯",
    ("狼队", "Armstrong, Adam James"): "亚当·阿姆斯特朗",
    ("狼队", "Arokodare, Toluwalase Emmanuel"): "阿罗科达雷",
    ("狼队", "Bellegarde, Jeanricner"): "贝勒加德",
    ("狼队", "Bentley, Daniel Ian"): "本特利",
    ("狼队", "Bueno Lopez, Hugo"): "乌戈·布埃诺",
    ("狼队", "Doherty, Matthew James"): "多赫蒂",
    ("狼队", "Gomes, Tote Antonio"): "托蒂·戈麦斯",
    ("狼队", "Gomes Da Silva, Joao Victor"): "若昂·戈麦斯",
    ("狼队", "Hwang, Hee-Chan"): "黄喜灿",
    ("狼队", "Ignacio Bueno, Santiago"): "圣地亚哥·布埃诺",
    ("狼队", "Johnstone, Samuel Luke"): "约翰斯通",
    ("狼队", "Krejci, Ladislav"): "克雷伊奇",
    ("狼队", "Malheiro De Sa, Jose Pedro"): "马列罗",
    ("狼队", "Mosquera Valdelamar, Yerson"): "莫斯克拉",
    ("狼队", "Tchatchoua, Jackson"): "查查瓦",
    ("狼队", "Trindade Da Costa Neto, Andre"): "安德烈",
}


def main() -> int:
    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as f:
        rows = list(csv.DictReader(f))
        fieldnames = list(rows[0].keys()) if rows else []

    if "player_name_cn" not in fieldnames:
        idx = fieldnames.index("player_name") + 1
        fieldnames.insert(idx, "player_name_cn")
        for row in rows:
            row["player_name_cn"] = ""

    updated = 0
    for row in rows:
        key = (row.get("team", "").strip(), row.get("player_name", "").strip())
        if key in NAME_MAP and not row.get("player_name_cn", "").strip():
            row["player_name_cn"] = NAME_MAP[key]
            updated += 1

    with CSV_PATH.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"filled_player_name_cn={updated}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

